
CREATE TABLE catches (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         species VARCHAR(255) NOT NULL CHECK (species IN ('CARP','BREAM','TENCH','CATFISH','PIKE','PERCH','ROACH','RUDD')),
                         weight DOUBLE PRECISION NOT NULL,
                         distance DOUBLE PRECISION,
                         location VARCHAR(255),
                         notes VARCHAR(1024),
                         caught_at TIMESTAMP(6) NOT NULL,
                         rig_info VARCHAR(255),
                         bait_info VARCHAR(255)
);